# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    uses: https://github.com/etechteam6/actionstest/action-shared.yml@main

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:


